---
- name: Ensure CopyQ config directory exists
  ansible.builtin.file:
    path: "{{ local_home }}/.config/copyq"
    state: directory
    mode: "0700"
  when: common_install_copyq
  become: false
  tags:
    - copyq

- name: Ensure CopyQ commands init
  ansible.builtin.copy:
    src: "copyq-commands.ini"
    dest: "{{ local_home }}/.config/copyq/copyq-commands.ini"
    mode: "0600"
  when: common_install_copyq
  become: false
  tags:
    - copyq
